name = "maybe-finance"
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[build]
command = "echo 'No build command specified'"

[env.production]
workers_dev = true
